#nullable enable
#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrmSync.Dataverse.Context
{
	
	
	/// <summary>
	/// A component dependency in CRM.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dependency")]
	public partial class Dependency : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the dependency entity
		/// </summary>
		public partial class Fields
		{
			public const string DependencyId = "dependencyid";
			public const string Id = "dependencyid";
			public const string DependencyNode_Ancestor_Dependency = "dependencynode_ancestor_dependency";
			public const string DependencyNode_Descendent_Dependency = "dependencynode_descendent_dependency";
			public const string DependencyType = "dependencytype";
			public const string DependencyTypeName = "dependencytypename";
			public const string DependentComponentBaseSolutionId = "dependentcomponentbasesolutionid";
			public const string DependentComponentNodeId = "dependentcomponentnodeid";
			public const string DependentComponentObjectId = "dependentcomponentobjectid";
			public const string DependentComponentParentId = "dependentcomponentparentid";
			public const string DependentComponentType = "dependentcomponenttype";
			public const string DependentComponentTypeName = "dependentcomponenttypename";
			public const string RequiredComponentBaseSolutionId = "requiredcomponentbasesolutionid";
			public const string RequiredComponentIntroducedVersion = "requiredcomponentintroducedversion";
			public const string RequiredComponentNodeId = "requiredcomponentnodeid";
			public const string RequiredComponentObjectId = "requiredcomponentobjectid";
			public const string RequiredComponentParentId = "requiredcomponentparentid";
			public const string RequiredComponentType = "requiredcomponenttype";
			public const string RequiredComponentTypeName = "requiredcomponenttypename";
			public const string VersionNumber = "versionnumber";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public Dependency(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public Dependency(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public Dependency(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public Dependency() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "dependencyid";
		
		public const string EntitySchemaName = "Dependency";
		
		public const string EntityLogicalName = "dependency";
		
		public const string EntityLogicalCollectionName = "dependencies";
		
		public const string EntitySetName = "dependencies";
		
		/// <summary>
		/// Unique identifier of a dependency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencyid")]
		public System.Nullable<System.Guid> DependencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("dependencyid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencyid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				base.Id = value;
			}
		}
		
		/// <summary>
		/// The dependency type of the dependency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencytype")]
		public virtual DependencyType? DependencyType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DependencyType?)(EntityOptionSetEnum.GetEnum(this, "dependencytype")));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencytypename")]
		public string? DependencyTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dependencytype"))
				{
					return this.FormattedValues["dependencytype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponentbasesolutionid")]
		public System.Nullable<System.Guid> DependentComponentBaseSolutionId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("dependentcomponentbasesolutionid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the dependent component's node.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponentnodeid")]
		public Microsoft.Xrm.Sdk.EntityReference? DependentComponentNodeId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dependentcomponentnodeid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponentobjectid")]
		public System.Nullable<System.Guid> DependentComponentObjectId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("dependentcomponentobjectid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponentparentid")]
		public System.Nullable<System.Guid> DependentComponentParentId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("dependentcomponentparentid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponenttype")]
		public virtual ComponentType? DependentComponentType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((ComponentType?)(EntityOptionSetEnum.GetEnum(this, "dependentcomponenttype")));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponenttypename")]
		public string? DependentComponentTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dependentcomponenttype"))
				{
					return this.FormattedValues["dependentcomponenttype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentbasesolutionid")]
		public System.Nullable<System.Guid> RequiredComponentBaseSolutionId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("requiredcomponentbasesolutionid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentintroducedversion")]
		public System.Nullable<double> RequiredComponentIntroducedVersion
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("requiredcomponentintroducedversion");
			}
		}
		
		/// <summary>
		/// Unique identifier of the required component's node
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentnodeid")]
		public Microsoft.Xrm.Sdk.EntityReference? RequiredComponentNodeId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("requiredcomponentnodeid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentobjectid")]
		public System.Nullable<System.Guid> RequiredComponentObjectId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("requiredcomponentobjectid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentparentid")]
		public System.Nullable<System.Guid> RequiredComponentParentId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("requiredcomponentparentid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponenttype")]
		public virtual ComponentType? RequiredComponentType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((ComponentType?)(EntityOptionSetEnum.GetEnum(this, "requiredcomponenttype")));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponenttypename")]
		public string? RequiredComponentTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("requiredcomponenttype"))
				{
					return this.FormattedValues["requiredcomponenttype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 dependencynode_ancestor_dependency
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentnodeid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dependencynode_ancestor_dependency")]
		public XrmSync.Dataverse.Context.DependencyNode? DependencyNode_Ancestor_Dependency
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmSync.Dataverse.Context.DependencyNode>("dependencynode_ancestor_dependency", null);
			}
		}
		
		/// <summary>
		/// N:1 dependencynode_descendent_dependency
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponentnodeid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dependencynode_descendent_dependency")]
		public XrmSync.Dataverse.Context.DependencyNode? DependencyNode_Descendent_Dependency
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmSync.Dataverse.Context.DependencyNode>("dependencynode_descendent_dependency", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public Dependency(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["dependencyid"] = base.Id;
                        break;
                    case "dependencyid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
