#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDomain.Context
{
	
	
	/// <summary>
	/// If there has been initial communication with this lead.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum InitialCommunication
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Contacted", 0)]
		Contacted = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Contacted", 1)]
		NotContacted = 1,
	}
}
#pragma warning restore CS1591
