<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>XrmSync.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
		<AssemblyName>XrmSync.$(MSBuildProjectName)</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DataverseConnection" Version="1.2.2" />
		<PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.2.10" />
		<PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Model\Model.csproj" />
	</ItemGroup>

</Project>
