name: CI Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Set version from CHANGELOG.md
        shell: pwsh
        run: ./scripts/Set-VersionFromChangelog.ps1 -ChangelogPath CHANGELOG.md -CsprojPath XrmSync/XrmSync.csproj
      - name: Restore dependencies
        run: dotnet restore XrmSync.sln
      - name: Build
        run: dotnet build XrmSync.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test XrmSync.sln --no-build --configuration Release --verbosity normal
      - name: Test analyzers
        shell: pwsh
        run: ./scripts/Test-Samples.ps1 -SkipBuild -OutputNormalizedJson -Configuration Release
      - name: Pack NuGet package
        run: dotnet pack XrmSync/XrmSync.csproj --no-build --configuration Release --output XrmSync/nupkg
      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: XrmSync/nupkg/*.nupkg
      - name: Upload analyzer JSON results
        uses: actions/upload-artifact@v4
        with:
          name: analyzer-results
          path: test-outputs/*.json
